### ISSUE TITLE
Will_paginate broke my app

### ISSUE THREAD

**Issue by vladanm** [tolk/tolk#62]
Using Tolk, in the app that is using Kaminari, instead of Will_paginate will break that App.
Cost me a Friday night. I forked it now, and ill try to change it so it can use Kaminari.
Be careful about this, if you are not using will_paginate.

**Comment by forever-ram** [comment]
same issue with Alchemy gem. Alchemy use kaminari gem.
  NoMethodError undefined method `per' for #<Alchemy::Language::ActiveRecord_Relation:0xb3cf4370> 

and solution 
  Kaminari.configure do |config|
    config.page_method_name = :per_page_kaminari
  end

wouldn't work's for me.
why not tolk uses kaminari instead of will_paginate?
Please let me know what is the real solution for the issue.

**Comment by lime** [comment]
The way [radar/forem](https://github.com/radar/forem) solved this looks like a good way to go: The README instructs you to install either `will_paginate` or `kaminari`, and will work with either, but does not add them as dependencies on its own.

These are the rows where that abstraction happens: [application_controller.rb:14-24](https://github.com/radar/forem/blob/ebaaa08/app/controllers/forem/application_controller.rb#L14-L24). See also [this comment](https://github.com/radar/forem/issues/38#issuecomment-2057134) which outlines the change.

What do you think, does this look like a feasible solution for `tolk`?

**Comment by lime** [comment]
Well, I gave it a shot. See #97 for a possible solution (sorry for the number of references above).

**Comment by meysammeisam** [comment]
@lime
I changed it to use kaminari using your changes.
github.com/meysammeisam/kaminariTolk
